argo:
  namespace: argocd
  project: default
  server: https://kubernetes.default.svc
  sourceRepo:
    url: https://github.com/SJoon99/SandBox-Infra.git
    branch: main

applications:
  rucio-config:
    enabled: true
    namespace: rucio
    syncWave: "-1"
    source:
      path: argocd/apps/03-platform/rucio/config

  rucio-server:
    enabled: true
    namespace: rucio
    syncWave: "0"
    source:
      chart: rucio-server
      repoURL: https://rucio.github.io/helm-charts
      targetRevision: 39.0.0
      helm:
        valueFiles:
          - argocd/apps/03-platform/rucio/rucio-server/values.yaml

  rucio-daemons:
    enabled: true
    namespace: rucio
    syncWave: "1"
    source:
      chart: rucio-daemons
      repoURL: https://rucio.github.io/helm-charts
      targetRevision: 39.0.0
      helm:
        valueFiles:
          - argocd/apps/03-platform/rucio/rucio-daemons/values.yaml

  # rucio-probes:
  #   enabled: true
  #   namespace: rucio
  #   syncWave: "2"
  #   source:
  #     path: argocd/apps/03-platform/rucio/rucio-probes/values.yaml
  
  # rucio-webui:
  #   enabled: true
  #   namespace: rucio
  #   syncWave: "3"
  #   source:   
  #     path: argocd/apps/03-platform/rucio/rucio-webui/values.yaml
