argo:
  namespace: argocd
  project: default
  server: https://kubernetes.default.svc
  sourceRepo:
    url: https://github.com/SJoon99/SandBox-Infra.git
    branch: main

applications:
  cert-manager:
    enabled: true
    namespace: cert-manager
    syncWave: "0"
    source:
      path: argocd/apps/00-infra/cert-manager/base

  cert-manager-certificate:
    enabled: true
    namespace: cert-manager
    syncWave: "1"
    source:
      path: argocd/apps/00-infra/cert-manager/certificate
