USER-SUPPLIED VALUES:
MTU: 0
autoDirectNodeRoutes: false
bandwidthManager:
  bbr: false
  enabled: false
bgpControlPlane:
  enabled: false
bpf:
  hostLegacyRouting: false
  mapDynamicSizeRatio: 0.0025
  masquerade: false
  monitorAggregation: medium
  preallocateMaps: false
certgen:
  image:
    repository: quay.io/cilium/certgen
    tag: v0.2.4
cgroup:
  autoMount:
    enabled: true
  hostRoot: /run/cilium/cgroupv2
cluster:
  id: 0
  name: default
cni:
  exclusive: true
  logFile: /var/run/cilium/cilium-cni.log
debug:
  enabled: false
enableIPv4Masquerade: true
enableIPv6Masquerade: true
encryption:
  enabled: false
envoy:
  image:
    repository: quay.io/cilium/cilium-envoy
    tag: v1.34.7-1757592137-1a52bb680a956879722f48c591a2ca90f7791324
extraArgs: []
extraConfig: {}
extraVolumeMounts: []
extraVolumes: []
gatewayAPI:
  enabled: true
healthPort: 9879
hostFirewall:
  enabled: false
hubble:
  enabled: false
  export:
    dynamic:
      config:
        content:
        - excludeFilters: []
          fieldMask: []
          filePath: /var/run/cilium/hubble/events.log
          includeFilters: []
          name: all
      enabled: false
    fileMaxBackups: 5
    fileMaxSizeMb: 10
  metrics:
    enabled: []
  peerService:
    clusterDomain: cluster.local
  relay:
    enabled: false
    image:
      repository: quay.io/cilium/hubble-relay
      tag: v1.18.2
  ui:
    backend:
      image:
        repository: quay.io/cilium/hubble-ui-backend
        tag: v0.13.3
    enabled: false
    frontend:
      image:
        repository: quay.io/cilium/hubble-ui
        tag: v0.13.3
identityAllocationMode: crd
image:
  repository: quay.io/cilium/cilium
  tag: v1.18.2
ingressController:
  enabled: true
ipMasqAgent:
  enabled: false
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4MaskSize: 24
    clusterPoolIPv4PodCIDRList:
    - 10.233.64.0/18
    clusterPoolIPv6MaskSize: 120
    clusterPoolIPv6PodCIDRList:
    - fd85:ee78:d8a6:8607::1:0000/112
ipv4:
  enabled: true
ipv4NativeRoutingCIDR: 10.233.64.0/18
ipv6:
  enabled: false
ipv6NativeRoutingCIDR: ""
k8sServiceHost: auto
k8sServicePort: auto
kubeProxyReplacement: true
nodePort:
  enabled: true
  bindProtection: true
autoProtectNodePortRange: true
l2announcements:
  enabled: true
loadBalancer:
  interface: wg1
loadbalancer:
  mode: snat
operator:
  enabled: true
  extraArgs: []
  extraVolumeMounts: []
  extraVolumes: []
  image:
    repository: quay.io/cilium/operator
    tag: v1.18.2
  replicas: 2
  tolerations:
  - operator: Exists
policyAuditMode: false
routingMode: tunnel
tunnelProtocol: vxlan
