argo:
  namespace: argocd
  project: default
  server: https://kubernetes.default.svc
  sourceRepo:
    url: https://github.com/SJoon99/SandBox-Infra.git
    branch: main

applications:
  # cilium-base:
  #   enabled: true
  #   namespace: kube-system
  #   syncWave: "-1"
  #   source:
  #     chart: cilium
  #     repoURL: https://helm.cilium.io/
  #     targetRevision: 1.18.3
  #     helm:
  #       valueFiles:
  #         - argocd/apps/00-infra/cilium/base/values.yaml

  cilium-svc:
    enabled: true
    namespace: kube-system
    syncWave: "0"
    source:
      path: argocd/apps/00-infra/cilium/base


  # cilium-gateway:
  #   enabled: true
  #   namespace: default
  #   syncWave: "1"
  #   source:
  #     path: argocd/apps/00-infra/cilium/gateway

  # cilium-routes:
  #   enabled: true
  #   namespace: argocd
  #   syncWave: "2"
  #   source:
  #     path: argocd/apps/00-infra/cilium/routes
